/**
 * A few color related utilities
 **/
export declare let labelColors: string[];
export declare let colorMap: {
    "Caption": string;
    "Image": string;
    "CharRun": string;
    "CharRunBegin": string;
    "CharRunBaseline": string;
    "FontBaseline": string;
    "LeftAlignedCharCol": string;
    "RightAlignedCharCol": string;
    "LeftAlignedColEnd": string;
    "HPageDivider": string;
    "ColLeftEvidence": string;
    "ColRightEvidence": string;
    "PageLines": string;
    "HLinePath": string;
    "VLinePath": string;
    "LinePath": string;
    "OutlineBox": string;
};
export declare let SolarColor: {
    base03: string;
    base02: string;
    base01: string;
    base00: string;
    base0: string;
    base1: string;
    base2: string;
    base3: string;
    yellow: string;
    orange: string;
    red: string;
    magenta: string;
    violet: string;
    blue: string;
    cyan: string;
    green: string;
};
export declare let Color: {
    Snow: string;
    GhostWhite: string;
    WhiteSmoke: string;
    Gainsboro: string;
    FloralWhite: string;
    OldLace: string;
    Linen: string;
    AntiqueWhite: string;
    PapayaWhip: string;
    BlanchedAlmond: string;
    Bisque: string;
    PeachPuff: string;
    NavajoWhite: string;
    Moccasin: string;
    Cornsilk: string;
    Ivory: string;
    LemonChiffon: string;
    Seashell: string;
    Honeydew: string;
    MintCream: string;
    Azure: string;
    AliceBlue: string;
    Lavender: string;
    LavenderBlush: string;
    MistyRose: string;
    White: string;
    Black: string;
    DarkSlateGray: string;
    DimGray: string;
    SlateGray: string;
    LightSlateGray: string;
    Gray: string;
    LightGray: string;
    MidnightBlue: string;
    Navy: string;
    NavyBlue: string;
    CornflowerBlue: string;
    DarkSlateBlue: string;
    SlateBlue: string;
    MediumSlateBlue: string;
    LightSlateBlue: string;
    MediumBlue: string;
    RoyalBlue: string;
    Blue: string;
    DodgerBlue: string;
    DeepSkyBlue: string;
    SkyBlue: string;
    LightSkyBlue: string;
    SteelBlue: string;
};
export declare let HighContrast: string[];
