/**
 * Some helper functions for working with client-side html
 */
export declare function $id(selector: string): JQuery<HTMLElement>;
export declare function mkNbsp(n: number): Text;
declare class JQNodeCtors {
    nbsp: typeof mkNbsp;
    a: (...args: (string | object)[]) => JQuery<HTMLElement>;
    abbr: (...args: (string | object)[]) => JQuery<HTMLElement>;
    acronym: (...args: (string | object)[]) => JQuery<HTMLElement>;
    address: (...args: (string | object)[]) => JQuery<HTMLElement>;
    applet: (...args: (string | object)[]) => JQuery<HTMLElement>;
    area: (...args: (string | object)[]) => JQuery<HTMLElement>;
    article: (...args: (string | object)[]) => JQuery<HTMLElement>;
    aside: (...args: (string | object)[]) => JQuery<HTMLElement>;
    audio: (...args: (string | object)[]) => JQuery<HTMLElement>;
    b: (...args: (string | object)[]) => JQuery<HTMLElement>;
    base: (...args: (string | object)[]) => JQuery<HTMLElement>;
    basefont: (...args: (string | object)[]) => JQuery<HTMLElement>;
    bdi: (...args: (string | object)[]) => JQuery<HTMLElement>;
    bdo: (...args: (string | object)[]) => JQuery<HTMLElement>;
    big: (...args: (string | object)[]) => JQuery<HTMLElement>;
    blockquote: (...args: (string | object)[]) => JQuery<HTMLElement>;
    body: (...args: (string | object)[]) => JQuery<HTMLElement>;
    br: (...args: (string | object)[]) => JQuery<HTMLElement>;
    button: (...args: (string | object)[]) => JQuery<HTMLElement>;
    canvas: (...args: (string | object)[]) => JQuery<HTMLElement>;
    caption: (...args: (string | object)[]) => JQuery<HTMLElement>;
    center: (...args: (string | object)[]) => JQuery<HTMLElement>;
    cite: (...args: (string | object)[]) => JQuery<HTMLElement>;
    code: (...args: (string | object)[]) => JQuery<HTMLElement>;
    col: (...args: (string | object)[]) => JQuery<HTMLElement>;
    colgroup: (...args: (string | object)[]) => JQuery<HTMLElement>;
    data: (...args: (string | object)[]) => JQuery<HTMLElement>;
    datalist: (...args: (string | object)[]) => JQuery<HTMLElement>;
    dd: (...args: (string | object)[]) => JQuery<HTMLElement>;
    del: (...args: (string | object)[]) => JQuery<HTMLElement>;
    details: (...args: (string | object)[]) => JQuery<HTMLElement>;
    dfn: (...args: (string | object)[]) => JQuery<HTMLElement>;
    dialog: (...args: (string | object)[]) => JQuery<HTMLElement>;
    dir: (...args: (string | object)[]) => JQuery<HTMLElement>;
    div: (...args: (string | object)[]) => JQuery<HTMLElement>;
    dl: (...args: (string | object)[]) => JQuery<HTMLElement>;
    dt: (...args: (string | object)[]) => JQuery<HTMLElement>;
    em: (...args: (string | object)[]) => JQuery<HTMLElement>;
    embed: (...args: (string | object)[]) => JQuery<HTMLElement>;
    fieldset: (...args: (string | object)[]) => JQuery<HTMLElement>;
    figcaption: (...args: (string | object)[]) => JQuery<HTMLElement>;
    figure: (...args: (string | object)[]) => JQuery<HTMLElement>;
    font: (...args: (string | object)[]) => JQuery<HTMLElement>;
    footer: (...args: (string | object)[]) => JQuery<HTMLElement>;
    form: (...args: (string | object)[]) => JQuery<HTMLElement>;
    frame: (...args: (string | object)[]) => JQuery<HTMLElement>;
    frameset: (...args: (string | object)[]) => JQuery<HTMLElement>;
    h1: (...args: (string | object)[]) => JQuery<HTMLElement>;
    h2: (...args: (string | object)[]) => JQuery<HTMLElement>;
    h3: (...args: (string | object)[]) => JQuery<HTMLElement>;
    h4: (...args: (string | object)[]) => JQuery<HTMLElement>;
    h5: (...args: (string | object)[]) => JQuery<HTMLElement>;
    h6: (...args: (string | object)[]) => JQuery<HTMLElement>;
    head: (...args: (string | object)[]) => JQuery<HTMLElement>;
    header: (...args: (string | object)[]) => JQuery<HTMLElement>;
    hr: (...args: (string | object)[]) => JQuery<HTMLElement>;
    html: (...args: (string | object)[]) => JQuery<HTMLElement>;
    i: (...args: (string | object)[]) => JQuery<HTMLElement>;
    iframe: (...args: (string | object)[]) => JQuery<HTMLElement>;
    img: (...args: (string | object)[]) => JQuery<HTMLElement>;
    input: (...args: (string | object)[]) => JQuery<HTMLElement>;
    ins: (...args: (string | object)[]) => JQuery<HTMLElement>;
    kbd: (...args: (string | object)[]) => JQuery<HTMLElement>;
    label: (...args: (string | object)[]) => JQuery<HTMLElement>;
    legend: (...args: (string | object)[]) => JQuery<HTMLElement>;
    li: (...args: (string | object)[]) => JQuery<HTMLElement>;
    link: (...args: (string | object)[]) => JQuery<HTMLElement>;
    main: (...args: (string | object)[]) => JQuery<HTMLElement>;
    map: (...args: (string | object)[]) => JQuery<HTMLElement>;
    mark: (...args: (string | object)[]) => JQuery<HTMLElement>;
    menu: (...args: (string | object)[]) => JQuery<HTMLElement>;
    menuitem: (...args: (string | object)[]) => JQuery<HTMLElement>;
    meta: (...args: (string | object)[]) => JQuery<HTMLElement>;
    meter: (...args: (string | object)[]) => JQuery<HTMLElement>;
    nav: (...args: (string | object)[]) => JQuery<HTMLElement>;
    noframes: (...args: (string | object)[]) => JQuery<HTMLElement>;
    noscript: (...args: (string | object)[]) => JQuery<HTMLElement>;
    ol: (...args: (string | object)[]) => JQuery<HTMLElement>;
    optgroup: (...args: (string | object)[]) => JQuery<HTMLElement>;
    option: (...args: (string | object)[]) => JQuery<HTMLElement>;
    output: (...args: (string | object)[]) => JQuery<HTMLElement>;
    p: (...args: (string | object)[]) => JQuery<HTMLElement>;
    param: (...args: (string | object)[]) => JQuery<HTMLElement>;
    picture: (...args: (string | object)[]) => JQuery<HTMLElement>;
    pre: (...args: (string | object)[]) => JQuery<HTMLElement>;
    progress: (...args: (string | object)[]) => JQuery<HTMLElement>;
    q: (...args: (string | object)[]) => JQuery<HTMLElement>;
    rp: (...args: (string | object)[]) => JQuery<HTMLElement>;
    rt: (...args: (string | object)[]) => JQuery<HTMLElement>;
    ruby: (...args: (string | object)[]) => JQuery<HTMLElement>;
    s: (...args: (string | object)[]) => JQuery<HTMLElement>;
    samp: (...args: (string | object)[]) => JQuery<HTMLElement>;
    script: (...args: (string | object)[]) => JQuery<HTMLElement>;
    section: (...args: (string | object)[]) => JQuery<HTMLElement>;
    select: (...args: (string | object)[]) => JQuery<HTMLElement>;
    small: (...args: (string | object)[]) => JQuery<HTMLElement>;
    source: (...args: (string | object)[]) => JQuery<HTMLElement>;
    span: (...args: (string | object)[]) => JQuery<HTMLElement>;
    strike: (...args: (string | object)[]) => JQuery<HTMLElement>;
    strong: (...args: (string | object)[]) => JQuery<HTMLElement>;
    style: (...args: (string | object)[]) => JQuery<HTMLElement>;
    sub: (...args: (string | object)[]) => JQuery<HTMLElement>;
    summary: (...args: (string | object)[]) => JQuery<HTMLElement>;
    sup: (...args: (string | object)[]) => JQuery<HTMLElement>;
    table: (...args: (string | object)[]) => JQuery<HTMLElement>;
    tbody: (...args: (string | object)[]) => JQuery<HTMLElement>;
    td: (...args: (string | object)[]) => JQuery<HTMLElement>;
    textarea: (...args: (string | object)[]) => JQuery<HTMLElement>;
    tfoot: (...args: (string | object)[]) => JQuery<HTMLElement>;
    th: (...args: (string | object)[]) => JQuery<HTMLElement>;
    thead: (...args: (string | object)[]) => JQuery<HTMLElement>;
    time: (...args: (string | object)[]) => JQuery<HTMLElement>;
    title: (...args: (string | object)[]) => JQuery<HTMLElement>;
    tr: (...args: (string | object)[]) => JQuery<HTMLElement>;
    track: (...args: (string | object)[]) => JQuery<HTMLElement>;
    tt: (...args: (string | object)[]) => JQuery<HTMLElement>;
    u: (...args: (string | object)[]) => JQuery<HTMLElement>;
    ul: (...args: (string | object)[]) => JQuery<HTMLElement>;
    video: (...args: (string | object)[]) => JQuery<HTMLElement>;
    wbr: (...args: (string | object)[]) => JQuery<HTMLElement>;
}
export declare const t: JQNodeCtors;
export declare const icon: {
    fa: (icn: string) => JQuery<HTMLElement>;
    trash: JQuery<HTMLElement>;
    hashtag: JQuery<HTMLElement>;
    chevronRight: JQuery<HTMLElement>;
    chevronLeft: JQuery<HTMLElement>;
};
export declare function makeModal(form: JQuery<HTMLElement>): JQuery<HTMLElement>;
export declare const htm: {
    labeledTextInput: (label: string, key: string) => JQuery<HTMLElement>;
    labeledTextboxInput: (label: string, key: string) => JQuery<HTMLElement>;
    labeledFileInput: (label: string, key: string) => JQuery<HTMLElement>;
    iconButton: (iconName: string) => JQuery<HTMLElement>;
    makeRadios(name: string, values: any[]): JQuery<HTMLElement>;
    makeToggle(name: string, checkedIcon: string, uncheckedIcon: string, initCheck: boolean, tooltip: string): JQuery<HTMLElement>;
};
export {};
