* Watrcolor client file organization

** Vue Components
**** filter-engine


** Client UI current file set
**** frame.js
    common page element setup for UI: topbar, menubar, site nav
    - [ ] Vue-ify

**** auth.js
    login/signup forms
    tsec-based cookie set/remove functions
    
    - [ ] Integrate auth0, Vue-ify

**** colors.js
    consts for rgb/solarized/etc color themes (replace with chroma.js)

**** coord-sys.ts
    Geometric shape classes, conversions, constructors.
 
**** d3-extras.js
    d3.js helper functions
    stepper transition animation helper functions (prob. obsolete)

**** dragselect.js
    d3.js based rect. selection function

**** graphpaper-variants.js
    graph paper like classes that use cell-based addressing to render grid-like visualizations
    used for textgrid rendering.
    has canvas, svg, fabric.js implementations

**** Infobar.js
    Cell-based output widget, mostly used as an in-app debug and dev logging tool

**** labeling.js
    label chooser dialog.
    annotation shape updates on PDF page images

**** LodashPlus.ts
    util funcs based on lodash

**** modals.js
    create a modal dialog, get user input, return as json via promise

**** MouseHandlerSets.js
    abstraction over sets of mouse handling funcs, for easier use when making textgrid based tools

**** schemas.js
    json validation functions for checking incoming data

**** serverApi.js
    rest crud server helper stuff

**** ServerDataExchange.js
    wrapper around server crud api, allows pub/sub to changes in server data

**** shared-state.js
    globally accessible data, consts, global mouse tracking init.

**** SplitWin.js
    window splitting, creation, deletion library

**** Tooltips.js
    tippy.js based tooltip class. not working atm.

**** tstags.ts
    jquery-based html tag creation library

**** utils.ts
    misc. utility functions


*** Extracted Text Visualizers (Page Image Overlays)

**** PageImageListWidget.js
    Wrapper around list of PageImageWidget 
    instantiates each PageImageWidget, has own status bar
    communicates with server on updates/deletions to labeling

**** PageImageWidget.js
    Individual page image 
    RTree for glyphs, annotations, 
    tooltips on hover
    glyph hover reticles
    glyph hover broadcast
    selection rect for region-based labeling



*** Extracted Text Visualizers (Plain Text)
**** view-pdf-text.js
    commented out early version of TextgridWidget
    contains sync-scroll code (commented out)

**** ReflowTools.js
    TextReflow helper tools: labeling, slicing, joining, reordering

**** ReflowWidgetInit.js
    Initialize or show/hide a text reflow widget for area-based label

**** ReflowWidget.js
    text reflow labeling widget

**** TextgridWidget.ts
    classes to display extracted PDF text, with highlights over labeled spans,
    glyph hovering, click sync to pdf page images.

**** rtrees.js
    helper functions for initializing rtrees with glyph and label data  
