// import Vue from "vue";

import {
  VApp,
  VContent,
  VLayout,
  VFlex,
  VPagination,
  VCard,
  VCardTitle,
  VCardActions,
  VBtn,
  VImg,
  VInput,
  VTextField,
  VNavigationDrawer,
  VContainer,
  VFooter,
  VToolbar,
  // VToolbarSideIcon,
  VToolbarTitle,
  VSpacer,
  VIcon,
  VList,
  // VListTile,
  // VListTileTitle,
  // VListTileAction,
  // VListTileContent,
  VDivider,
} from "vuetify/lib";

export const opts = {
  components: {
    VApp,
    VContent,
    VLayout,
    VFlex,
    VPagination,
    VCard,
    VCardTitle,
    VCardActions,
    VTextField,
    VBtn,
    VImg,
    VInput,
    VNavigationDrawer,
    VToolbar,
    VContainer,
    VFooter,
    // VToolbarSideIcon,
    VToolbarTitle,
    VSpacer,
    VIcon,
    VList,
    // VListTile,
    // VListTileTitle,
    // VListTileAction,
    // VListTileContent,
    VDivider,
  },
  // theme: {
  //   primary: "#ee44aa",
  //   secondary: "#424242",
  //   accent: "#82B1FF",
  //   error: "#FF5252",
  //   info: "#2196F3",
  //   success: "#4CAF50",
  //   warning: "#FFC107",
  // },
  customProperties: true,
  // iconfont: "md",
};

